USER_ALREADY_EXISTS = 'user_already_exists'
RECORD_NOT_FOUND = 'record_not_found'
CREDENTIALS_INVALID = 'credentials_invalid'
TOKEN_EXPIRED = 'token_expired'
UNIQUE_GENERATION_FAILED = 'unique_slug_generation_failed'