"""add name index in item

Revision ID: 3f001d660ab0
Revises: 358b7aa33515
Create Date: 2022-12-22 13:07:28.814543

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3f001d660ab0'
down_revision = '358b7aa33515'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_name'), table_name='item')
    # ### end Alembic commands ###
